name: deploy nexturl to vercel
on: [push, pull_request]
jobs:
  vercel: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #add env file to .env.local
      - name: Set Env Vars on Vercel Project
        uses: dkershner6/vercel-set-env-action@v1
        with:
          token: Tghkta0MrOCkzxG9j7goKHcH
          teamId: cryptsky # optional, without will use personal
          projectName: hlsa-task22 # project name in Vercel
          envVariableKeys: MONGODB_URL,MONGODB_DB
        env:
          MONGODB_URL: mongodb+srv://admin:admin@cluster0.cg1wb.mongodb.net/database?retryWrites=true&w=majority
          TARGET_MONGODB_URL: preview,development,production # comma delimited, one of [production, preview, development]
          TYPE_MONGODB_URL: encrypted # one of [plain, encrypted]
          MONGODB_DB: database
          TARGET_MONGODB_DB: preview,development,production
          TYPE_MONGODB_DB: encrypted
          
      # deploy app to vercel
      - name: deploy site to vercel      
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: "Tghkta0MrOCkzxG9j7goKHcH" #Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 
          vercel-args: '--prod' #Optional
          vercel-org-id: ${{ secrets.ORG_ID}}  #Required
          vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
